# Generated by Django 4.1.9 on 2023-06-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdivision',
            old_name='principal_location',
            new_name='principal_location_orig',
        ),
        migrations.RenameField(
            model_name='businessgroup',
            old_name='principal_location_8',
            new_name='principal_location_nb',
        ),
        migrations.RenameField(
            model_name='businessgroup',
            old_name='principal_location_9',
            new_name='principal_location_orig',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='registrar_company_9',
            new_name='registrar_company_orig',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='registrar_iana_id_9',
            new_name='registrar_iana_id_orig',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='registration_emails_9',
            new_name='registration_emails_orig',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='status_9',
            new_name='status_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='architectural_model_1',
            new_name='architectural_model',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='env_used_for_1',
            new_name='env_used_for',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='geo_region_9',
            new_name='geo_region_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='hostname_9',
            new_name='hostname_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='impacted_division_9',
            new_name='impacted_division_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='impacted_group_9',
            new_name='impacted_group_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='location_9',
            new_name='location_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='owners_9',
            new_name='owners_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='private_ip_9',
            new_name='private_ip_1',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='public_ip_9',
            new_name='public_ip_1',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='status_9',
            new_name='status_orig',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='vendor_company_1',
            new_name='vendor_company_fk',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='vendor_pocs_9',
            new_name='vendor_pocs_orig',
        ),
        migrations.RenameField(
            model_name='sitelocation',
            old_name='geo_region_9',
            new_name='geo_region_orig',
        ),
        migrations.RenameField(
            model_name='sitelocation',
            old_name='impacted_division',
            new_name='impacted_division_orig',
        ),
        migrations.RenameField(
            model_name='sitelocation',
            old_name='impacted_group',
            new_name='impacted_group_orig',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='registrar_company',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='cloud_provider_9',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='feature_auth_type',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='support_group_website_approvals',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='support_group_website_technical',
        ),
        migrations.AddField(
            model_name='fqdn',
            name='cloud_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='feature_webauth_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='fqdn_status_orig',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fqdns',
                to='wim.fqdnstatus',
            ),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='geo_region_choice',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='support_group_website_approvals_orig',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='support_group_website_technical_orig',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='vendor_company_orig',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='website_status_orig',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fqdns',
                to='wim.websitestatus',
            ),
        ),
        migrations.AddField(
            model_name='sitelocation',
            name='geo_region_choice',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='webserverframework',
            name='raw_banner',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='businessdivision',
            name='acronym',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdivision',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='businessgroup',
            name='acronym',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wim.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='fqdn_status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='website_status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Registrar',
        ),
    ]
