# Generated by Django 4.1.9 on 2023-06-03 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0003_rename_redirect_status_9_fqdn_redirect_status_orig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='geo_region_orig',
        ),
        migrations.RemoveField(
            model_name='sitelocation',
            name='geo_region_orig',
        ),
    ]
