# Generated by Django 4.1.9 on 2023-06-05 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0005_alter_sitelocation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='confidence',
            new_name='confidence_orig',
        ),
    ]
