# Generated by Django 4.1.9 on 2023-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0007_remove_domain_status_orig_domain_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='confidence_orig',
        ),
        migrations.AlterField(
            model_name='domain',
            name='confidence',
            field=models.CharField(default='Candidate', max_length=50),
        ),
    ]
