# Generated by Django 4.1.9 on 2023-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0009_rename_mandates_pentesting_9_complianceprogram_mandates_pentesting_orig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='architectural_model',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='env_used_for',
        ),
        migrations.AddField(
            model_name='fqdn',
            name='tech_webserver_orig',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
