# Generated by Django 4.1.9 on 2023-06-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0010_remove_fqdn_architectural_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='architectural_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='env_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
