# Generated by Django 4.1.9 on 2023-06-06 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0011_fqdn_architectural_model_fqdn_env_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fqdn',
            old_name='tls_version',
            new_name='tls_version_int',
        ),
    ]
