# Generated by Django 4.1.9 on 2023-06-06 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0013_fqdn_tls_protocol_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fqdn',
            old_name='website_email',
            new_name='website_email_orig',
        ),
    ]
