# Generated by Django 4.1.9 on 2023-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0014_rename_website_email_fqdn_website_email_orig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='snow_bcdr_criticality',
        ),
    ]
