# Generated by Django 4.1.9 on 2023-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0015_remove_fqdn_snow_bcdr_criticality'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='private_ip_2',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='asset_class',
            field=models.CharField(default='FQDN', max_length=50),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
