# Generated by Django 4.1.9 on 2023-06-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0017_fqdn_asset_confidence_fqdn_status_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='domain',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wim.domain'
            ),
        ),
    ]
