# Generated by Django 4.1.9 on 2023-06-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0018_alter_fqdn_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='fqdn_status',
            field=models.CharField(default='0-Unknown-Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='vendor_company_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='fqdns',
                to='wim.vendor',
            ),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='vendor_company_orig',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='vendor_pocs_orig',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='website_status',
            field=models.CharField(default='0-Unknown-Test', max_length=50),
        ),
    ]
