# Generated by Django 4.1.9 on 2023-06-08 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0019_alter_fqdn_fqdn_status_alter_fqdn_vendor_company_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='private_ip_1',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='private_ip_2',
        ),
    ]
