# Generated by Django 4.1.9 on 2023-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0020_remove_fqdn_private_ip_1_remove_fqdn_private_ip_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='private_ip_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='private_ip_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
