# Generated by Django 4.1.9 on 2023-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0021_fqdn_private_ip_1_fqdn_private_ip_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
    ]
