# Generated by Django 4.1.9 on 2023-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0023_alter_fqdn_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
