# Generated by Django 4.1.9 on 2023-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0024_alter_fqdn_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ownership_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
