# Generated by Django 4.1.9 on 2023-06-09 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0025_domain_ownership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='confidence',
            new_name='asset_confidence',
        ),
    ]
