# Generated by Django 4.1.9 on 2023-06-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0026_rename_confidence_domain_asset_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='parked_status',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='redirect_status_orig',
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='domain',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fqdns',
                to='wim.domain',
            ),
        ),
    ]
