# Generated by Django 4.1.9 on 2023-06-13 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0027_remove_fqdn_parked_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='site_operation_age',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
