# Generated by Django 4.1.9 on 2023-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0028_alter_fqdn_site_operation_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='mark_triaging',
            field=models.BooleanField(default=False),
        ),
    ]
