# Generated by Django 4.1.9 on 2023-06-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0029_fqdn_mark_triaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='platform_type',
            field=models.CharField(default='Server', max_length=50),
        ),
    ]
