# Generated by Django 4.1.9 on 2023-06-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0031_rename_build_operatingsystem_build_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='cpe',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wim.cpe'
            ),
        ),
    ]
