# Generated by Django 4.1.9 on 2023-06-14 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0032_alter_operatingsystem_cpe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceprogram',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='fqdnstatus',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='websiteauthtype',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='websitestatus',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='compliance_programs',
        ),
        migrations.DeleteModel(
            name='CloudProvider',
        ),
        migrations.DeleteModel(
            name='ComplianceProgram',
        ),
        migrations.DeleteModel(
            name='FqdnStatus',
        ),
        migrations.DeleteModel(
            name='WebsiteAuthType',
        ),
        migrations.DeleteModel(
            name='WebsiteStatus',
        ),
    ]
