# Generated by Django 4.1.9 on 2023-06-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0033_remove_complianceprogram_tags_remove_fqdnstatus_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='compliance_programs_choice',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
