# Generated by Django 4.1.9 on 2023-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0035_alter_webserverframework_cpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='scan_fingerprint_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
