# Generated by Django 4.1.9 on 2023-06-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0036_fqdn_scan_fingerprint_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='description',
        ),
        migrations.AddField(
            model_name='cpe',
            name='cpe_friendly',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
