# Generated by Django 4.1.9 on 2023-07-25 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0039_rename_last_vuln_assessment_fqdn_date_last_pentest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fqdn',
            old_name='vuln_scan_last_date',
            new_name='date_last_vulnscan',
        ),
    ]
