# Generated by Django 4.1.9 on 2023-08-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0041_remove_webemail_comments_webemail_name_webemail_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdn',
            name='is_nonprod_mirror',
            field=models.BooleanField(default=False),
        ),
    ]
