# Generated by Django 4.1.9 on 2023-09-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0048_rename_webserverframework_software_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ('name',), 'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AddField(
            model_name='fqdn',
            name='software',
            field=models.ManyToManyField(blank=True, related_name='fqdns', to='wim.software'),
        ),
        migrations.AlterField(
            model_name='software',
            name='cpe',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='software',
                to='wim.cpe',
            ),
        ),
    ]
