# Generated by Django 4.1.9 on 2023-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0049_alter_software_options_fqdn_software_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='tls_cert_is_wildcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='tls_cert_self_signed',
            field=models.BooleanField(default=False),
        ),
    ]
