# Generated by Django 4.1.9 on 2023-09-28 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0050_alter_fqdn_tls_cert_is_wildcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='tech_webserver_1',
        ),
    ]
