# Generated by Django 4.1.9 on 2023-09-28 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0051_remove_fqdn_tech_webserver_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={
                'ordering': ['name'],
                'verbose_name': 'Operating System',
                'verbose_name_plural': 'Operating Systems',
            },
        ),
        migrations.AlterUniqueTogether(
            name='operatingsystem',
            unique_together=set(),
        ),
    ]
