# Generated by Django 4.1.9 on 2023-12-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0054_remove_fqdn_tls_version_int_fqdn_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hash_md5',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
