# Generated by Django 4.1.9 on 2023-12-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0055_alter_certificate_hash_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='certificate',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wim.certificate'
            ),
        ),
    ]
