# Generated by Django 4.1.9 on 2024-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0056_alter_fqdn_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='icn',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='iorg',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='san',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='scn',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
