# Generated by Django 4.1.9 on 2024-02-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wim', '0057_alter_certificate_icn_alter_certificate_iorg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='idn',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sdn',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
